import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.util.ArrayList;

public class TablePanel extends JPanel {
    JTable table;
    JScrollPane scrollPane;
    private final String[] col = {"White count", "Hispanic count", "Black count", "Asian count", "Male count", "Female count"};

    public TablePanel() throws IOException {
        FileReader f = new FileReader();
        setPreferredSize(new Dimension(200, 50));
        setBackground(Color.pink);

        Object[][]CCdataArray = getData(f.getArrayList());

        // Create the JTable with the dataArray and column names
        table = new JTable(CCdataArray, col);

        table.setPreferredSize(new Dimension(250, 20));

        // Create the JScrollPane and set its preferred size
        scrollPane = new JScrollPane(table);
        scrollPane.setPreferredSize(new Dimension(600, 100));
        add(scrollPane, BorderLayout.NORTH);

    }
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        int x = 30;
        int y = 400;
        g.setFont(new Font("Arial", Font.BOLD, 15));

        String[] description = {
        "Above shows a table displaying the predictions for the ethnicities and genders of"
       ,"the future members of the California City Council and School Board. This data was"
       ,"generated by previous, real-world data that showed the number of genders/ethnicities"
       ,"that served the California City Council and School Board from 2010 to 2023. To"
       ,"reiterate, this data is computer-generated and are predictions. To learn more"
       ,"about this data/study, visit the link at the top of 'Main.java'."

        };

        for (String s : description)
            g.drawString(s, x, y += g.getFontMetrics().getHeight() + 20);


    }

    public Object[][] getData(ArrayList<Long> data) {

        int n = col.length; // Number of columns
        Object[][] dataArray = new Object[1][n];

        for (int j = 0; j < n; j++) {
            if (j < data.size()) {
                dataArray[0][j] = data.get(j);
           }
        }
        return dataArray;
    }
}
